source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPFormTable_Example', :exclusive => true do
  pod 'POPFormTable', :path => '../'
end

target 'POPFormTable_Tests', :exclusive => true do
  pod 'POPFormTable', :path => '../'

  
end
