source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPFormTable_Example'do
  pod 'POPFormTable', :path => '../'
  target 'POPFormTable_Tests' do
  	inherit! :search_paths
  end
end


